Bump to kind v0.11.0
istio/common-files pull request #428
Opened 2021-05-27 23:49 UTC by howardjohn

2021-05-28 05:15 UTC, mandarjog commented on files/common/scripts/setup_env.sh
> +  export IMAGE_VERSION=master-2021-05-27T21-48-48
Can you point to build tools commit that has version 0.11.0?

2021-05-28 05:18 UTC, howardjohn commented on files/common/scripts/setup_env.sh
> +  export IMAGE_VERSION=master-2021-05-27T21-48-48
https://github.com/istio/tools/pull/1553/files

2021-05-28 15:16 UTC, mandarjog approved these changes
Lgtm

2021-05-28 15:54 UTC, ericvn commented
Note that we are currently using kind 0.11.1 with the latest image.

2021-05-28 20:05 UTC, istio-testing commented
@howardjohn: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-06-01 14:34 UTC, ericvn requested changes
We have moved to a newer version of kind, so merging this will revert that change.

2021-06-01 14:52 UTC, closed without merging