chore: fix run as root issue
istio/common-files pull request #718
Opened 2022-11-16 07:13 UTC by daixiang0

`make shell` returns error:

```
root:[ztunnel]$ make shell
useradd: UID 0 is not unique
groups: cannot find name for group ID 998 <===
build-tools:/work# id
uid=0(root) gid=998 groups=998
```

If run as root, no need to map uid&gid, and docker group does not exist.

Signed-off-by: Loong <loong.dai@intel.com>

2022-11-16 17:24 UTC, howardjohn requested changes
Without:
```
$ make shell
groups: cannot find name for group ID 996
```

With this PR:
```
 ~/go/src/istio.io/istio (experimental-ambient)
$ make shell
docker: Error response from daemon: unable to find user  576696: no matching entries in passwd file.
make: *** [Makefile:50: shell] Error 125
```

2022-11-17 02:05 UTC, daixiang0 commented
@howardjohn thanks, I have fixed it, the root cause is about param pass.

```
long@dev:~/ztunnel$ make shell
build-tools:/work$ ls
boringssl-fips  BUGS-AND-FEATURE-REQUESTS.md  build.rs  Cargo.lock  Cargo.toml  common  CONTRIBUTING.md  examples  LICENSE  LOCAL.md  Makefile  Makefile.core.mk  Makefile.overrides.mk  out  proto  README.md  scripts  src  SUPPORT.md  tests
build-tools:/work$
```

2022-11-23 02:05 UTC, daixiang0 commented
ping @howardjohn

2022-11-23 14:53 UTC, howardjohn approved these changes

2022-11-23 14:55 UTC, merged